/**
 * Representative groupon.es style data.
 */
import type {
  UserRow,
  CategoryRow,
  LocationRow,
  MerchantRow,
  DealRow,
  DealOptionRow,
  DealReviewRow,
} from "@/db/schema";

/** Seed users carry a plaintext dev password; seed.ts hashes it into password_hash. */
type UserSeed = Pick<UserRow, "id" | "name" | "email"> & { password: string };
type CategorySeed = CategoryRow;
type LocationSeed = LocationRow;
type MerchantSeed = MerchantRow;
type DealSeed = DealRow;
type DealReviewSeed = DealReviewRow;
type DealOptionSeed = Omit<DealOptionRow, "discount_pct">;

export const users: UserSeed[] = [
  { id: 1, name: "Laura G.", email: "laura@example.com", password: "password123" },
  { id: 2, name: "Carlos M.", email: "carlos@example.com", password: "password123" },
  { id: 3, name: "Ana R.", email: "ana@example.com", password: "password123" },
  { id: 4, name: "Javier S.", email: "javier@example.com", password: "password123" },
  { id: 5, name: "Marta L.", email: "marta@example.com", password: "password123" },
  { id: 6, name: "Diego P.", email: "diego@example.com", password: "password123" },
];

export const categories: CategorySeed[] = [
  { id: 1, slug: "wellness-beauty", name: "Belleza y Bienestar" },
  { id: 2, slug: "restaurants", name: "Restaurantes" },
  { id: 3, slug: "activities", name: "Ocio y Aventura" },
  { id: 4, slug: "travel", name: "Viajes y Hoteles" },
  { id: 5, slug: "fitness", name: "Deporte y Fitness" },
  { id: 6, slug: "home-services", name: "Hogar y Servicios" },
];

export const locations: LocationSeed[] = [
  { id: 1, slug: "madrid", name: "Madrid", region: "Comunidad de Madrid" },
  { id: 2, slug: "barcelona", name: "Barcelona", region: "Cataluña" },
  { id: 3, slug: "valencia", name: "Valencia", region: "Comunidad Valenciana" },
  { id: 4, slug: "sevilla", name: "Sevilla", region: "Andalucía" },
  { id: 5, slug: "malaga", name: "Málaga", region: "Andalucía" },
];

export const merchants: MerchantSeed[] = [
  { id: 1, name: "Spa Aqua Urban", location_id: 1 },
  { id: 2, name: "Restaurante La Brasa", location_id: 1 },
  { id: 3, name: "Karting Madrid Sur", location_id: 1 },
  { id: 4, name: "Hotel Centro Madrid", location_id: 1 },
  { id: 5, name: "CrossFit Box Chamberí", location_id: 1 },
  { id: 6, name: "Manos Limpias Hogar", location_id: 1 },
  { id: 7, name: "Thai Massage BCN", location_id: 2 },
  { id: 8, name: "Tapas & Vins", location_id: 2 },
  { id: 9, name: "Escape Room Gòtic", location_id: 2 },
  { id: 10, name: "Hotel Rambla Mar", location_id: 2 },
  { id: 11, name: "Beauty Lounge VLC", location_id: 3 },
  { id: 12, name: "Arrocería El Palmar", location_id: 3 },
  { id: 13, name: "Hammam Andalusí", location_id: 4 },
  { id: 14, name: "Mesón Triana", location_id: 4 },
  { id: 15, name: "Sunset Spa Marbella", location_id: 5 },
  { id: 16, name: "Chiringuito El Faro", location_id: 5 },
];

export const deals: DealSeed[] = [
  // --- Madrid ---
  {
    id: 1,
    title: "Circuito spa para dos",
    description:
      "Acceso al circuito termal con sauna, jacuzzi y baño turco para dos personas.",
    category_id: 1,
    merchant_id: 1,
    location_id: 1,
    fine_print: "Reserva previa obligatoria. No válido festivos.",
    valid_until: "2026-12-31",
    is_active: true,
  },
  {
    id: 2,
    title: "Masaje deportivo descontracturante",
    description:
      "Masaje de cuerpo completo realizado por fisioterapeutas titulados.",
    category_id: 1,
    merchant_id: 1,
    location_id: 1,
    fine_print: "Cita con 48h de antelación.",
    valid_until: "2026-12-31",
    is_active: true,
  },
  {
    id: 3,
    title: "Menú degustación a la brasa",
    description: "Cocina de autor a la brasa con maridaje de vinos.",
    category_id: 2,
    merchant_id: 2,
    location_id: 1,
    fine_print: "Bebidas extra no incluidas.",
    valid_until: "2026-10-31",
    is_active: true,
  },
  {
    id: 4,
    title: "Hamburguesa gourmet con bebida",
    description: "Hamburguesa de vacuno madurado con patatas y bebida.",
    category_id: 2,
    merchant_id: 2,
    location_id: 1,
    fine_print: "Válido de lunes a jueves.",
    valid_until: "2026-09-30",
    is_active: true,
  },
  {
    id: 5,
    title: "Karting en circuito outdoor",
    description: "Sesión de karting cronometrada con equipamiento incluido.",
    category_id: 3,
    merchant_id: 3,
    location_id: 1,
    fine_print: "Altura mínima 1,40 m.",
    valid_until: "2026-11-30",
    is_active: true,
  },
  {
    id: 6,
    title: "Escapada en hotel 4* en el centro",
    description:
      "Habitación doble con desayuno buffet en pleno centro de Madrid.",
    category_id: 4,
    merchant_id: 4,
    location_id: 1,
    fine_print: "Sujeto a disponibilidad. No válido en puentes.",
    valid_until: "2026-12-15",
    is_active: true,
  },
  {
    id: 7,
    title: "Bono mensual de CrossFit",
    description: "Acceso a clases de CrossFit con coach certificado.",
    category_id: 5,
    merchant_id: 5,
    location_id: 1,
    fine_print: "Solo nuevos clientes.",
    valid_until: "2026-12-31",
    is_active: true,
  },
  {
    id: 8,
    title: "Limpieza del hogar a domicilio",
    description: "Servicio de limpieza profesional con productos incluidos.",
    category_id: 6,
    merchant_id: 6,
    location_id: 1,
    fine_print: "Radio de 15 km del centro.",
    valid_until: "2026-10-31",
    is_active: true,
  },

  // --- Barcelona ---
  {
    id: 9,
    title: "Masaje tailandés tradicional",
    description:
      "Auténtico masaje tailandés con estiramientos y digitopresión.",
    category_id: 1,
    merchant_id: 7,
    location_id: 2,
    fine_print: "Reserva previa.",
    valid_until: "2026-12-31",
    is_active: true,
  },
  {
    id: 10,
    title: "Ritual facial antiedad",
    description:
      "Tratamiento facial con limpieza, peeling y mascarilla antiedad.",
    category_id: 1,
    merchant_id: 7,
    location_id: 2,
    fine_print: "No acumulable con otras ofertas.",
    valid_until: "2026-11-30",
    is_active: true,
  },
  {
    id: 11,
    title: "Tapas y vino para dos",
    description: "Selección de tapas de temporada con vino de la casa.",
    category_id: 2,
    merchant_id: 8,
    location_id: 2,
    fine_print: "Cenas previa reserva.",
    valid_until: "2026-10-31",
    is_active: true,
  },
  {
    id: 12,
    title: "Brunch de fin de semana",
    description:
      "Brunch con bebida caliente, zumo natural y plato principal a elegir.",
    category_id: 2,
    merchant_id: 8,
    location_id: 2,
    fine_print: "Solo sábados y domingos.",
    valid_until: "2026-09-30",
    is_active: true,
  },
  {
    id: 13,
    title: "Escape room en el Barrio Gótico",
    description:
      "Sala de escape ambientada de 60 minutos para hasta 4 jugadores.",
    category_id: 3,
    merchant_id: 9,
    location_id: 2,
    fine_print: "Edad mínima 12 años.",
    valid_until: "2026-12-31",
    is_active: true,
  },
  {
    id: 14,
    title: "Hotel frente al mar",
    description: "Estancia en habitación doble con vistas al mar y desayuno.",
    category_id: 4,
    merchant_id: 10,
    location_id: 2,
    fine_print: "Tasa turística no incluida.",
    valid_until: "2026-12-15",
    is_active: true,
  },

  // --- Valencia ---
  {
    id: 15,
    title: "Manicura y pedicura completa",
    description: "Manicura y pedicura con esmaltado semipermanente.",
    category_id: 1,
    merchant_id: 11,
    location_id: 3,
    fine_print: "Cita previa.",
    valid_until: "2026-11-30",
    is_active: true,
  },
  {
    id: 16,
    title: "Paella valenciana a leña",
    description: "Auténtica paella valenciana a leña con entrante y bebida.",
    category_id: 2,
    merchant_id: 12,
    location_id: 3,
    fine_print: "Encargo con 1 día de antelación.",
    valid_until: "2026-12-31",
    is_active: true,
  },

  // --- Sevilla ---
  {
    id: 17,
    title: "Baños árabes con masaje",
    description: "Recorrido por los baños termales con masaje aromático.",
    category_id: 1,
    merchant_id: 13,
    location_id: 4,
    fine_print: "Reserva previa obligatoria.",
    valid_until: "2026-12-31",
    is_active: true,
  },
  {
    id: 18,
    title: "Tapeo tradicional de Triana",
    description: "Ruta de tapas típicas con bebida incluida.",
    category_id: 2,
    merchant_id: 14,
    location_id: 4,
    fine_print: "Válido de martes a domingo.",
    valid_until: "2026-10-31",
    is_active: true,
  },

  // --- Málaga ---
  {
    id: 19,
    title: "Día de spa frente al mar",
    description:
      "Jornada de spa con circuito de aguas y opción de masaje en la playa.",
    category_id: 1,
    merchant_id: 15,
    location_id: 5,
    fine_print: "Aforo limitado, reserva previa.",
    valid_until: "2026-12-31",
    is_active: true,
  },
  {
    id: 20,
    title: "Pescaíto frito malagueño",
    description: "Pescaíto frito variado con ensalada y bebida.",
    category_id: 2,
    merchant_id: 16,
    location_id: 5,
    fine_print: "Terraza sujeta a disponibilidad.",
    valid_until: "2026-11-30",
    is_active: true,
  },

  // --- Inactive (exercises is_active filtering) ---
  {
    id: 21,
    title: "Menú de temporada agotado",
    description:
      "Oferta finalizada, conservada para verificar el filtrado por disponibilidad.",
    category_id: 2,
    merchant_id: 2,
    location_id: 1,
    fine_print: null,
    valid_until: "2024-01-01",
    is_active: false,
  },
];

export const dealOptions: DealOptionSeed[] = [
  {
    id: 1,
    deal_id: 1,
    title: "Circuito termal 90 min para dos",
    price: 39,
    original_price: 90,
  },
  {
    id: 2,
    deal_id: 1,
    title: "Circuito + masaje 30 min para dos",
    price: 55,
    original_price: 120,
  },
  { id: 3, deal_id: 2, title: "Masaje 30 min", price: 19, original_price: 40 },
  { id: 4, deal_id: 2, title: "Masaje 60 min", price: 25, original_price: 55 },
  {
    id: 5,
    deal_id: 3,
    title: "Menú degustación para dos",
    price: 49,
    original_price: 110,
  },
  {
    id: 6,
    deal_id: 3,
    title: "Menú degustación para cuatro",
    price: 95,
    original_price: 210,
  },
  {
    id: 7,
    deal_id: 4,
    title: "Hamburguesa + patatas + bebida",
    price: 9.9,
    original_price: 18,
  },
  {
    id: 8,
    deal_id: 5,
    title: "Tanda de 15 minutos",
    price: 19,
    original_price: 30,
  },
  {
    id: 9,
    deal_id: 5,
    title: "Dos tandas de 15 minutos",
    price: 34,
    original_price: 60,
  },
  {
    id: 10,
    deal_id: 6,
    title: "1 noche con desayuno",
    price: 69,
    original_price: 120,
  },
  {
    id: 11,
    deal_id: 6,
    title: "2 noches con desayuno",
    price: 129,
    original_price: 240,
  },
  {
    id: 12,
    deal_id: 7,
    title: "1 mes ilimitado",
    price: 39,
    original_price: 99,
  },
  {
    id: 13,
    deal_id: 8,
    title: "Limpieza de 3 horas",
    price: 35,
    original_price: 60,
  },
  {
    id: 14,
    deal_id: 8,
    title: "Limpieza de 5 horas",
    price: 55,
    original_price: 100,
  },
  {
    id: 15,
    deal_id: 9,
    title: "Masaje tailandés 60 min",
    price: 29,
    original_price: 65,
  },
  {
    id: 16,
    deal_id: 9,
    title: "Masaje tailandés 90 min",
    price: 39,
    original_price: 90,
  },
  {
    id: 17,
    deal_id: 10,
    title: "Ritual facial 75 min",
    price: 35,
    original_price: 80,
  },
  {
    id: 18,
    deal_id: 11,
    title: "6 tapas + 2 copas de vino",
    price: 25,
    original_price: 50,
  },
  {
    id: 19,
    deal_id: 12,
    title: "Brunch completo para dos",
    price: 19,
    original_price: 38,
  },
  {
    id: 20,
    deal_id: 13,
    title: "Sala para 4 personas",
    price: 39,
    original_price: 72,
  },
  {
    id: 21,
    deal_id: 14,
    title: "2 noches con desayuno",
    price: 129,
    original_price: 240,
  },
  {
    id: 22,
    deal_id: 15,
    title: "Manicura + pedicura semipermanente",
    price: 15,
    original_price: 35,
  },
  {
    id: 23,
    deal_id: 16,
    title: "Paella para dos",
    price: 29,
    original_price: 58,
  },
  {
    id: 24,
    deal_id: 16,
    title: "Menú de arroces para cuatro",
    price: 55,
    original_price: 99,
  },
  {
    id: 25,
    deal_id: 17,
    title: "Baños + masaje aromático 15 min",
    price: 29,
    original_price: 60,
  },
  {
    id: 26,
    deal_id: 17,
    title: "Circuito hammam para dos",
    price: 45,
    original_price: 90,
  },
  {
    id: 27,
    deal_id: 18,
    title: "4 tapas + bebida",
    price: 12,
    original_price: 24,
  },
  {
    id: 28,
    deal_id: 18,
    title: "Menú andaluz para dos",
    price: 27,
    original_price: 55,
  },
  {
    id: 29,
    deal_id: 19,
    title: "Día de spa con piscina",
    price: 49,
    original_price: 95,
  },
  {
    id: 30,
    deal_id: 19,
    title: "Masaje en la playa 45 min",
    price: 30,
    original_price: 60,
  },
  {
    id: 31,
    deal_id: 20,
    title: "Pescaíto para dos",
    price: 24,
    original_price: 48,
  },
  {
    id: 32,
    deal_id: 20,
    title: "Menú marinero para cuatro",
    price: 59,
    original_price: 110,
  },
  { id: 33, deal_id: 21, title: "Menú agotado", price: 10, original_price: 20 },
];

export const dealReviews: DealReviewSeed[] = [
  {
    id: 1,
    deal_id: 1,
    user_id: 1,
    rating: 5,
    comment: "Muy relajante, repetiremos.",
    created_at: "2026-01-15",
  },
  {
    id: 2,
    deal_id: 1,
    user_id: 2,
    rating: 4,
    comment: "Buena experiencia, algo concurrido.",
    created_at: "2026-02-03",
  },
  {
    id: 3,
    deal_id: 2,
    user_id: 1,
    rating: 4,
    comment: "Masaje muy bueno.",
    created_at: "2026-01-12",
  },
  {
    id: 4,
    deal_id: 3,
    user_id: 3,
    rating: 5,
    comment: "Comida excelente y trato genial.",
    created_at: "2026-01-20",
  },
  {
    id: 5,
    deal_id: 3,
    user_id: 4,
    rating: 5,
    comment: "El maridaje, espectacular.",
    created_at: "2026-03-10",
  },
  {
    id: 6,
    deal_id: 3,
    user_id: 5,
    rating: 4,
    comment: "Raciones generosas.",
    created_at: "2026-03-22",
  },
  {
    id: 7,
    deal_id: 5,
    user_id: 6,
    rating: 4,
    comment: "Divertidísimo, karts en buen estado.",
    created_at: "2026-02-11",
  },
  {
    id: 8,
    deal_id: 5,
    user_id: 1,
    rating: 5,
    comment: "Repetiré seguro.",
    created_at: "2026-04-01",
  },
  {
    id: 9,
    deal_id: 6,
    user_id: 2,
    rating: 4,
    comment: "Hotel céntrico y limpio.",
    created_at: "2026-01-30",
  },
  {
    id: 10,
    deal_id: 7,
    user_id: 6,
    rating: 5,
    comment: "Coaches top, gran ambiente.",
    created_at: "2026-02-01",
  },
  {
    id: 11,
    deal_id: 9,
    user_id: 3,
    rating: 5,
    comment: "El mejor masaje de Barcelona.",
    created_at: "2026-02-18",
  },
  {
    id: 12,
    deal_id: 9,
    user_id: 4,
    rating: 4,
    comment: "Muy profesionales.",
    created_at: "2026-03-05",
  },
  {
    id: 13,
    deal_id: 11,
    user_id: 5,
    rating: 4,
    comment: "Tapas ricas y vino correcto.",
    created_at: "2026-01-25",
  },
  {
    id: 14,
    deal_id: 11,
    user_id: 6,
    rating: 5,
    comment: "Ambiente inmejorable.",
    created_at: "2026-02-28",
  },
  {
    id: 15,
    deal_id: 11,
    user_id: 1,
    rating: 4,
    comment: "Buena relación calidad-precio.",
    created_at: "2026-04-12",
  },
  {
    id: 16,
    deal_id: 13,
    user_id: 2,
    rating: 5,
    comment: "Acertijos muy ingeniosos.",
    created_at: "2026-03-15",
  },
  {
    id: 17,
    deal_id: 13,
    user_id: 3,
    rating: 4,
    comment: "Nos lo pasamos genial.",
    created_at: "2026-04-20",
  },
  {
    id: 18,
    deal_id: 15,
    user_id: 3,
    rating: 4,
    comment: "Resultado impecable.",
    created_at: "2026-03-02",
  },
  {
    id: 19,
    deal_id: 16,
    user_id: 4,
    rating: 5,
    comment: "Paella auténtica, brutal.",
    created_at: "2026-02-09",
  },
  {
    id: 20,
    deal_id: 16,
    user_id: 5,
    rating: 5,
    comment: "La mejor que he probado.",
    created_at: "2026-03-30",
  },
  {
    id: 21,
    deal_id: 17,
    user_id: 6,
    rating: 5,
    comment: "Los baños son un templo de paz.",
    created_at: "2026-01-18",
  },
  {
    id: 22,
    deal_id: 17,
    user_id: 1,
    rating: 4,
    comment: "Relajante, masaje algo corto.",
    created_at: "2026-02-22",
  },
  {
    id: 23,
    deal_id: 19,
    user_id: 2,
    rating: 4,
    comment: "Spa muy completo.",
    created_at: "2026-03-08",
  },
  {
    id: 24,
    deal_id: 19,
    user_id: 3,
    rating: 5,
    comment: "Día perfecto frente al mar.",
    created_at: "2026-04-15",
  },
  {
    id: 25,
    deal_id: 20,
    user_id: 4,
    rating: 4,
    comment: "Pescaíto fresco y crujiente.",
    created_at: "2026-02-14",
  },
  {
    id: 26,
    deal_id: 20,
    user_id: 5,
    rating: 3,
    comment: "Bien, pero algo salado.",
    created_at: "2026-03-19",
  },
];
